name: FirstPlugin
version: '${project.version}'
main: me.spengui.firstplugin.FirstPlugin
api-version: 1.16
authors: [ SpenGUI ]
description: My first plugin
website: https://www.youtube.com/channel/UCbOSK7plfCiilId5haEq7Zg
commands:
  kill:
    description: You kill your self lmao
    usage: /<command>