name: FirstPlugin
version: '1.0-SNAPSHOT'
main: me.spengui.firstplugin.FirstPlugin
api-version: 1.16
authors: [ SpenGUI ]
description: My first plugin
website: https://www.youtube.com/channel/UCbOSK7plfCiilId5haEq7Zg
commands:
  die:
    description: You kill your self lmao
    usage: /<command>

